services:
  # Backend Service
  - type: web
    name: gestor-gastos-backend
    runtime: node
    env: node
    buildCommand: npm install --prefix gestor_gastos_backend
    startCommand: npm start --prefix gestor_gastos_backend
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PG_HOST
        value: aws-0-sa-east-1.pooler.supabase.com
      - key: PG_PORT
        value: 5432
      - key: PG_USER
        value: postgres.qazglqqykuplurfehcbz
      - key: PG_PASSWORD
        value: Jere060904_12
      - key: PG_DATABASE
        value: postgres
      - key: JWT_SECRET
        value: algosecreto_produccion_muy_seguro_2024
      - key: DB_URL
        value: postgresql://postgres.qazglqqykuplurfehcbz:Jere060904_12@aws-0-sa-east-1.pooler.supabase.com:5432/postgres
      - key: PORT
        value: 10000

  # Frontend Service
  - type: web
    name: gestor-gastos-frontend
    runtime: static
    buildCommand: |
      npm install --prefix gestor_gastos_frontend &&
      npm run build --prefix gestor_gastos_frontend
    staticPublishPath: gestor_gastos_frontend/dist
    buildFilter:
      paths:
        - gestor_gastos_frontend/**
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: gestor-gastos-backend
          property: host
        sync: false
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
