services:
  - type: web
    name: gestor-gastos-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --prefix gestor_gastos_backend
    startCommand: npm start --prefix gestor_gastos_backend
    rootDir: ./
    envVars:
      - key: NODE_ENV
        value: production
      - key: PG_HOST
        value: aws-0-sa-east-1.pooler.supabase.com
      - key: PG_PORT
        value: 5432
      - key: PG_USER
        value: postgres.hgipbefbrxfzlezmewtg
      - key: PG_PASSWORD
        value: Jere060904_12
      - key: PG_DATABASE
        value: postgres
      - key: JWT_SECRET
        value: algosecreto
      - key: PORT
        value: 3000

  - type: static
    name: gestor-gastos-frontend
    buildCommand: npm install --prefix gestor_gastos_frontend && npm run build --prefix gestor_gastos_frontend
    staticPublishPath: gestor_gastos_frontend/dist
    region: oregon
    plan: free
    rootDir: ./
    envVars:
      - key: VITE_API_URL
        value: https://gestor-gastos-backend.onrender.com
